In [1]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import RMSprop

Using TensorFlow backend.


In [2]:
data = [
    [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
]

# for i in range(1500):
#     for j in range(4):
#         data.append(data[j])

print(data)

[[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0]]


In [3]:
data = np.array(data)

train_X, train_Y = data[:,:2], data[:,2]

print(train_X)
print(train_Y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 0]


In [ ]:
# Testing best weight initialization
for i in range(1,11):
    model = Sequential()

    xavier = keras.initializers.glorot_normal(seed=i)

    model.add(Dense(2, activation='sigmoid', input_dim = 2, kernel_initializer=xavier))
    model.add(Dense(1, activation='sigmoid', kernel_initializer=xavier))

    rms = RMSprop(lr=0.001)

    model.compile(optimizer=rms,
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    model.fit(train_X, train_Y, epochs=2500, verbose=2, shuffle=True)

In [ ]:
# Working Model
model = Sequential()

xavier = keras.initializers.glorot_normal(seed=4)

model.add(Dense(2, activation='sigmoid', input_dim = 2, kernel_initializer=xavier))
model.add(Dense(1, activation='sigmoid', kernel_initializer=xavier))

rms = RMSprop(lr=0.001)

model.compile(optimizer=rms,
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_X, train_Y, epochs=5000, verbose=2, shuffle=True)

In [6]:
weight_layer1 = model.layers[0].get_weights()
weight_layer2 = model.layers[1].get_weights()

print(weight_layer1)
print(weight_layer2)

[array([[ 5.046769 ,  4.9747996],
       [-5.0586524, -4.8853645]], dtype=float32), array([-2.9637446,  2.7950175], dtype=float32)]
[array([[ 5.053264],
       [-4.891611]], dtype=float32), array([2.4203458], dtype=float32)]


In [7]:
ip = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

res = model.predict(ip)

print(res)

[[0.12548664]
 [0.8680398 ]
 [0.8833327 ]
 [0.12270248]]
