In [1]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


In [2]:
data = [
    [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
]

for i in range(1500):
    for j in range(4):
        data.append(data[j])

print(data)

[[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0], [0, 1, 1], [1, 0, 1]

In [3]:
data = np.array(data)

train_X, train_Y = data[:,:2], data[:,2]

print(train_X)
print(train_Y)

[[0 0]
 [0 1]
 [1 0]
 ...
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 ... 1 1 0]


In [ ]:
# Working Model

model = Sequential()

rd = keras.initializers.RandomNormal()

model.add(Dense(2, activation='sigmoid', input_dim = 2, kernel_initializer='glorot_uniform'))
model.add(Dense(1, activation='sigmoid', kernel_initializer='glorot_uniform'))

sgd = SGD(lr=0.1, momentum=0.0, decay=0.0, nesterov=False)

model.compile(optimizer=sgd,
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_X, train_Y, epochs=200, batch_size=100, verbose=2, shuffle=True)

In [57]:
model = Sequential()

rd = keras.initializers.RandomNormal()

model.add(Dense(4, activation='sigmoid', input_dim = 2, kernel_initializer='glorot_uniform'))
model.add(Dense(2, activation='sigmoid', kernel_initializer='glorot_uniform'))
model.add(Dense(1, activation='sigmoid', kernel_initializer='glorot_uniform'))

sgd = SGD(lr=0.1, momentum=0.0, decay=0.0, nesterov=False)

model.compile(optimizer=sgd,
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_X, train_Y, epochs=500, batch_size=100, verbose=2, shuffle=True)

Epoch 1/500
 - 3s - loss: 0.7140 - acc: 0.5000
Epoch 2/500
 - 0s - loss: 0.6935 - acc: 0.4820
Epoch 3/500
 - 1s - loss: 0.6932 - acc: 0.4802
Epoch 4/500
 - 1s - loss: 0.6933 - acc: 0.4958
Epoch 5/500
 - 1s - loss: 0.6932 - acc: 0.5008
Epoch 6/500
 - 1s - loss: 0.6932 - acc: 0.5012
Epoch 7/500
 - 1s - loss: 0.6932 - acc: 0.5335
Epoch 8/500
 - 1s - loss: 0.6932 - acc: 0.4724
Epoch 9/500
 - 1s - loss: 0.6932 - acc: 0.4895
Epoch 10/500
 - 1s - loss: 0.6932 - acc: 0.5346
Epoch 11/500
 - 0s - loss: 0.6933 - acc: 0.4845
Epoch 12/500
 - 1s - loss: 0.6932 - acc: 0.4888
Epoch 13/500
 - 1s - loss: 0.6932 - acc: 0.4857
Epoch 14/500
 - 1s - loss: 0.6933 - acc: 0.4619
Epoch 15/500
 - 1s - loss: 0.6931 - acc: 0.5018
Epoch 16/500
 - 1s - loss: 0.6932 - acc: 0.5055
Epoch 17/500
 - 1s - loss: 0.6932 - acc: 0.5075
Epoch 18/500
 - 1s - loss: 0.6932 - acc: 0.5087
Epoch 19/500
 - 1s - loss: 0.6932 - acc: 0.5215
Epoch 20/500
 - 1s - loss: 0.6931 - acc: 0.4993
Epoch 21/500
 - 1s - loss: 0.6932 - acc: 0.4892
E

Epoch 171/500
 - 1s - loss: 0.4885 - acc: 0.7500
Epoch 172/500
 - 0s - loss: 0.4874 - acc: 0.7500
Epoch 173/500
 - 1s - loss: 0.4865 - acc: 0.7500
Epoch 174/500
 - 1s - loss: 0.4851 - acc: 0.7500
Epoch 175/500
 - 1s - loss: 0.4838 - acc: 0.7500
Epoch 176/500
 - 1s - loss: 0.4824 - acc: 0.7500
Epoch 177/500
 - 1s - loss: 0.4808 - acc: 0.7500
Epoch 178/500
 - 1s - loss: 0.4792 - acc: 0.7500
Epoch 179/500
 - 1s - loss: 0.4774 - acc: 0.7500
Epoch 180/500
 - 0s - loss: 0.4754 - acc: 0.7500
Epoch 181/500
 - 0s - loss: 0.4731 - acc: 0.7500
Epoch 182/500
 - 0s - loss: 0.4706 - acc: 0.7500
Epoch 183/500
 - 0s - loss: 0.4679 - acc: 0.7500
Epoch 184/500
 - 0s - loss: 0.4647 - acc: 0.7500
Epoch 185/500
 - 0s - loss: 0.4611 - acc: 0.7500
Epoch 186/500
 - 0s - loss: 0.4568 - acc: 0.7500
Epoch 187/500
 - 1s - loss: 0.4521 - acc: 0.7500
Epoch 188/500
 - 1s - loss: 0.4466 - acc: 0.7500
Epoch 189/500
 - 1s - loss: 0.4400 - acc: 0.7500
Epoch 190/500
 - 1s - loss: 0.4323 - acc: 0.7500
Epoch 191/500
 - 1s 

KeyboardInterrupt: 

In [10]:
model = Sequential()

rd = keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=None)

model.add(Dense(2, activation='relu', input_dim = 2, kernel_initializer=rd))
model.add(Dense(1, activation='sigmoid', kernel_initializer=rd))

sgd = SGD(lr=0.05, momentum=0.0, decay=0.0, nesterov=False)

model.compile(optimizer=sgd,
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_X, train_Y, epochs=150, batch_size=25, verbose=2, shuffle=True)

Epoch 1/150
 - 2s - loss: 0.6932 - acc: 0.5017
Epoch 2/150
 - 2s - loss: 0.6932 - acc: 0.5030
Epoch 3/150
 - 2s - loss: 0.6927 - acc: 0.5296
Epoch 4/150
 - 1s - loss: 0.6896 - acc: 0.5650
Epoch 5/150
 - 2s - loss: 0.6743 - acc: 0.7102
Epoch 6/150
 - 2s - loss: 0.6225 - acc: 0.7500
Epoch 7/150
 - 2s - loss: 0.5482 - acc: 0.7500
Epoch 8/150
 - 2s - loss: 0.5069 - acc: 0.7500
Epoch 9/150
 - 2s - loss: 0.4920 - acc: 0.7500
Epoch 10/150
 - 2s - loss: 0.4862 - acc: 0.7500
Epoch 11/150
 - 1s - loss: 0.4835 - acc: 0.7500
Epoch 12/150


KeyboardInterrupt: 

In [259]:
weight_layer1 = model.layers[0].get_weights()
weight_layer2 = model.layers[1].get_weights()
# weight_layer3 = model.layers[2].get_weights()

print(weight_layer1)
print(weight_layer2)

[array([[ 3.0633574, -3.0627532],
       [-3.0634956,  3.062535 ]], dtype=float32), array([-0.00010618, -0.00022644], dtype=float32)]
[array([[4.3271203],
       [4.3279576]], dtype=float32), array([-5.783614], dtype=float32)]


In [260]:
ip = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

res = model.predict(ip)

print(res)

[[0.00306809]
 [0.99943036]
 [0.99943125]
 [0.00306809]]
